src/Enymind/Bundle/Health/SecureBundle/Entity/EntryType.php
<?php

namespace Enymind\Bundle\Health\SecureBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Enymind\Bundle\Health\SecureBundle\Entity\EntryType
 *
 * @ORM\Table(name="entry_types")
 * @ORM\Entity
 */
class EntryType
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer $owner_id
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="users")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner_id;
    
    /**
     * @ORM\OneToMany(targetEntity="EntryGroup", mappedBy="entry_types")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $groups;
    
    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=32)
     */
    private $name;

    /**
     * @var string $description
     *
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    /**
     * @var integer $min
     *
     * @ORM\Column(name="min", type="integer")
     */
    private $min;

    /**
     * @var integer $max
     *
     * @ORM\Column(name="max", type="integer")
     */
    private $max;

    /**
     * @var string $quantity
     *
     * @ORM\Column(name="quantity", type="string", length=16)
     */
    private $quantity;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set owner_id
     *
     * @param integer $ownerId
     * @return EntryType
     */
    public function setOwnerId($ownerId)
    {
        $this->owner_id = $ownerId;
    
        return $this;
    }

    /**
     * Get owner_id
     *
     * @return integer 
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }
    
    /**
     * Set name
     *
     * @param string $name
     * @return EntryType
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return EntryType
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set min
     *
     * @param integer $min
     * @return EntryType
     */
    public function setMin($min)
    {
        $this->min = $min;
    
        return $this;
    }

    /**
     * Get min
     *
     * @return integer 
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Set max
     *
     * @param integer $max
     * @return EntryType
     */
    public function setMax($max)
    {
        $this->max = $max;
    
        return $this;
    }

    /**
     * Get max
     *
     * @return integer 
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Set quantity
     *
     * @param string $quantity
     * @return EntryType
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
    
        return $this;
    }

    /**
     * Get quantity
     *
     * @return string 
     */
    public function getQuantity()
    {
        return $this->quantity;
    }
    
    /**
     * Get defalut_value
     *
     * @return integer 
     */
    public function getDefaultValue()
    {
        return $this->getMin() + ceil( ceil( $this->getMax() - $this->getMin() ) / 2 );
    }
}

src/Enymind/Bundle/Health/SecureBundle/Form/UserType.php
<?php

namespace Enymind\Bundle\Health\SecureBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('password')
            ->add('isActive')
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Enymind\Bundle\Health\SecureBundle\Entity\User'
        ));
    }

    public function getName()
    {
        return 'enymind_bundle_health_securebundle_usertype';
    }
}

src/Enymind/Bundle/Health/SecureBundle/Controller/DefaultController.php
<?php

namespace Enymind\Bundle\Health\SecureBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Enymind\Bundle\Health\SecureBundle\Entity\Entry;
use Enymind\Bundle\Health\SecureBundle\Entity\EntryType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    /**
     * @Route("/")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function indexAction()
    {
        return array();
    }
    
    /**
     * @Route("/enter")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function enterAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entryTypes = $em->getRepository('EnymindHealthSecureBundle:EntryType')->findBy(
                array("owner_id" => array( 1, $this->getUser()->getId() )), // where
                array("name" => "ASC") // order by
                );
      
        return array('entryTypes' => $entryTypes);
    }
    
    /**
     * @Route("/enter/{entryTypeId}")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function enterFormAction($entryTypeId)
    {
        $em = $this->getDoctrine()->getManager();
        $entryType = $em->getRepository('EnymindHealthSecureBundle:EntryType')->find($entryTypeId);
        
        if (!$entryType) {
            throw $this->createNotFoundException('Unable to find EntryType entity.');
        }
        
        if( $entryType->getOwnerId()->getId() != $this->getUser()->getId() &&
            $entryType->getOwnerId()->getId() != 1 ) {
            throw $this->createNotFoundException('EntryType entity not belognin to user.');
        }
        
        return array('entryType' => $entryType
            );
    }
    
    /**
     * @Route("/enter/{entryTypeId}/save")
     * @Method("POST")
     * @Secure(roles="ROLE_USER")
     */
    public function enterFormSaveAction(Request $request, $entryTypeId)
    {
        $value = $request->request->get('value');
        
        if ( empty( $value ) ) {
            throw $this->createNotFoundException('value not set.');
        }
      
        $em = $this->getDoctrine()->getManager();
        $entryType = $em->getRepository('EnymindHealthSecureBundle:EntryType')->find($entryTypeId);
        
        if (!$entryType) {
            throw $this->createNotFoundException('Unable to find EntryType entity.');
        }
        
        if( $entryType->getOwnerId()->getId() != $this->getUser()->getId() &&
            $entryType->getOwnerId()->getId() != 1 ) {
            throw $this->createNotFoundException('EntryType entity not belognin to user.');
        }
        
        $entry = new Entry();
        $entry->setTypeId( $entryType );
        $entry->setOwnerId( $this->getUser() );
        $entry->setValue( $value );
        
        $em->persist($entry);
        $em->flush();
      
        $this->get('session')->setFlash('notice', $this->get('translator')->trans('Your entry were added!') );
        
        $response = $this->forward('EnymindHealthSecureBundle:Default:index');
        return $response;
    }
    
    /**
     * @Route("/group")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function groupAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entryGroups = $em->getRepository('EnymindHealthSecureBundle:EntryGroup')->findBy(
                array("owner_id" => array( 1, $this->getUser()->getId() ),"visible" => "1"), // where
                array("name" => "ASC") // order by
                );
      
        return array('entryGroups' => $entryGroups);
    }
    
    /**
     * @Route("/group/{entryGroupId}")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function groupFormAction($entryGroupId)
    {
        $em = $this->getDoctrine()->getManager();
        $entryGroup = $em->getRepository('EnymindHealthSecureBundle:EntryGroup')->find($entryGroupId);
        
        if (!$entryGroup) {
            throw $this->createNotFoundException('Unable to find EntryGroup entity.');
        }
        
        if( $entryGroup->getOwnerId()->getId() != $this->getUser()->getId() &&
            $entryGroup->getOwnerId()->getId() != 1 ) {
            throw $this->createNotFoundException('EntryGroup entity not belognin to user.');
        }
        
        $entryTypes = array();
        
        foreach( $entryGroup->getEntryTypesArray() as $entryTypeId ) {
          $entryType = $em->getRepository('EnymindHealthSecureBundle:EntryType')->find($entryTypeId);
          
          if (!$entryType) {
              throw $this->createNotFoundException('Unable to find EntryType entity.');
          }

          if( $entryType->getOwnerId()->getId() != $this->getUser()->getId() &&
              $entryType->getOwnerId()->getId() != 1 ) {
              throw $this->createNotFoundException('EntryType entity not belognin to user.');
          }
          
          $entryTypes[] = $entryType;
        }
        
        return array('entryGroup' => $entryGroup,
                     'entryTypes' => $entryTypes
            );
    }
    
    /**
     * @Route("/group/{entryGroupId}/save")
     * @Method("POST")
     * @Secure(roles="ROLE_USER")
     */
    public function groupFormSaveAction(Request $request, $entryGroupId)
    {
        $values = $request->request->get('value');
        
        if ( count( $values ) == 0 ) {
            throw $this->createNotFoundException('values not set.');
        }
      
        $em = $this->getDoctrine()->getManager();
        $entryGroup = $em->getRepository('EnymindHealthSecureBundle:EntryGroup')->find($entryGroupId);
        
        if (!$entryGroup) {
            throw $this->createNotFoundException('Unable to find EntryGroup entity.');
        }
        
        if( $entryGroup->getOwnerId()->getId() != $this->getUser()->getId() &&
            $entryGroup->getOwnerId()->getId() != 1 ) {
            throw $this->createNotFoundException('EntryGroup entity not belognin to user.');
        }
        
        foreach( $entryGroup->getEntryTypesArray() as $index => $entryTypeId ) {
          $entryType = $em->getRepository('EnymindHealthSecureBundle:EntryType')->find($entryTypeId);

          if (!$entryType) {
              throw $this->createNotFoundException('Unable to find EntryType entity.');
          }

          if( $entryType->getOwnerId()->getId() != $this->getUser()->getId() &&
              $entryType->getOwnerId()->getId() != 1 ) {
              throw $this->createNotFoundException('EntryType entity not belognin to user.');
          }
          
          $entry = new Entry();
          $entry->setTypeId( $entryType );
          $entry->setOwnerId( $this->getUser() );
          $entry->setValue( $values[$index] );

          $em->persist($entry);
        }
        
        $em->flush();
      
        $this->get('session')->setFlash('notice', $this->get('translator')->trans('Your group were added!') );
        
        $response = $this->forward('EnymindHealthSecureBundle:Default:index');
        return $response;
    }
    
    /**
     * @Route("/stats")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function statsAction()
    {
        return array();
    }
    
    /**
     * @Route("/stats/data")
     * @Secure(roles="ROLE_USER")
     */
    public function statsDataAction()
    {
        $entries = $this->getUser()->getEntries();
        
        $entriesByType = array();
        foreach( $entries as $entry ) {
          $entriesByType[ $entry->getTypeId()->getName() ][] = $entry;
        }
        
        $results = array();
        foreach( $entriesByType as $typeName => $entries ) {
          $result = array('label' => $typeName );
          foreach( $entries as $entry ) {
            $result['data'][]=array($entry->getAdded()->getTimestamp(), $entry->getValue());
          }
          $results[ $typeName ] = $result;
        }
        
        $response = new Response();
        $response->setContent( json_encode($results) );
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }
    
    /**
     * @Route("/report")
     * @Secure(roles="ROLE_USER")
     * @Template()
     */
    public function reportAction()
    {
        return array('entries' => $this->getUser()->getEntries());
    }
}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/enter.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-enter{% endblock %}

{% block header %}
  <a href="/secure" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Enter entry{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <ul data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{% trans %}Search entry type...{% endtrans %}" data-filter-theme="c" data-theme="c" data-divider-theme="c">
  {% for entryType in entryTypes %}
    <li><a href="/secure/enter/{{ entryType.id }}">{{ entryType.name }}</a></li>
  {% endfor %}
  </ul>

{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/enterForm.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-enter-form{% endblock %}

{% block header %}
  <a href="/secure/enter" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Enter entry value{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <form class="multi_form" action="/secure/enter/{{ entryType.id }}/save" method="post" id="entry-form">
    <div class="multi_part">
      <h3>{{ entryType.name }}</h3>
      <p>{{ entryType.description }}. {% trans %}Value in{% endtrans %} <strong>{{ entryType.quantity }}</strong></p>
      <input type="range" name="value" id="value-slider-fill" value="{{ entryType.defaultValue }}" min="{{ entryType.min }}" max="{{ entryType.max }}" data-highlight="true" />
    </div>
    <button type="submit" name="submit" value="submit" data-icon="check" data-theme="b">{% trans %}Add entry{% endtrans %}</button>
  </form>
{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/group.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-group{% endblock %}

{% block header %}
  <a href="/secure" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Enter group{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <ul data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{% trans %}Search entry group...{% endtrans %}" data-filter-theme="c" data-theme="c" data-divider-theme="c">
  {% for entryGroup in entryGroups %}
    <li><a href="/secure/group/{{ entryGroup.id }}">{{ entryGroup.name }}</a></li>
  {% endfor %}
  </ul>

{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/groupForm.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-group-form{% endblock %}

{% block header %}
  <a href="/secure/group" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Enter entry values{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <form class="multi_form" action="/secure/group/{{ entryGroup.id }}/save" method="post" id="entry-form">
    {% for entryType in entryTypes %}
      <div class="multi_part">
        <h3>{{ entryType.name }}</h3>
        <p>{{ entryType.description }}. {% trans %}Value in{% endtrans %} <strong>{{ entryType.quantity }}</strong>.</p>
        <input type="range" name="value[]" id="value-slider-fill" value="{{ entryType.defaultValue }}" min="{{ entryType.min }}" max="{{ entryType.max }}" data-highlight="true" />
      </div>
    {% endfor %}
    <button type="submit" name="submit" value="submit" data-icon="check" data-theme="b">{% trans %}Add entry{% endtrans %}</button>
  </form>
{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-index{% endblock %}
{% block datadomcache %}true{% endblock %}

{% block header %}
  <a href="/secure/logout" data-icon="delete" data-theme="d">{% trans %}Log Out{% endtrans %}</a>
  <h1>{% trans %}Dashboard{% endtrans %}</h1>
  <a href="/secure/help" data-icon="search" class="ui-disabled" data-theme="b" data-iconpos="right" data-prefetch>{% trans %}Help{% endtrans %}</a>
{% endblock %}

{% block body %}
  <div class="ui-grid-a">
    <div class="ui-block-a"><a href="/secure/enter" data-iconpos="top" data-icon="plus" data-role="button" data-theme="b" data-prefetch>{% trans %}Enter value{% endtrans %}</a></div>
    <div class="ui-block-b"><a href="/secure/group" data-iconpos="top" data-icon="plus" data-role="button" data-theme="b" data-prefetch>{% trans %}Enter group{% endtrans %}</a></div>
    <div class="ui-block-a"><a href="/secure/stats" data-iconpos="top" data-icon="bar-chart" data-role="button" data-theme="c">{% trans %}Statistics{% endtrans %}</a></div>
    <div class="ui-block-b"><a href="/secure/report" data-iconpos="top" data-icon="credit-card" data-role="button" data-theme="c">{% trans %}Reporting{% endtrans %}</a></div>
  </div>
  <div>
    <img src="{{ asset("/bundles/enymindhealthwelcome/images/bacteria.png") }}" style="float: right; padding: 10px" />
    <p><strong>{% trans %}Entries in system:{% endtrans %}</strong> N/a</p>
  </div>
  <div class="ui-grid-a" style="clear: both;">
    <div class="ui-block-a"><a href="/secure/manage/types" data-iconpos="top" data-icon="gear" data-role="button" data-theme="c">{% trans %}Manage types{% endtrans %}</a></div>
    <div class="ui-block-b"><a href="/secure/manage/group" data-iconpos="top" data-icon="gear" data-role="button" data-theme="c">{% trans %}Manage groups{% endtrans %}</a></div>
    <div class="ui-block-a"><a href="/secure/manage/pool" class="ui-disabled" data-iconpos="top" data-icon="gear" data-role="button" data-theme="c">{% trans %}Manage pools{% endtrans %}</a></div>
    <div class="ui-block-b"><a href="/secure/manage" class="ui-disabled" data-iconpos="top" data-icon="gear" data-role="button" data-theme="a">{% trans %}Settings{% endtrans %}</a></div>
  </div>
{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/report.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-report{% endblock %}

{% block header %}
  <a href="/secure" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Report{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <ul data-role="listview" data-theme="d" data-divider-theme="c" id="report-ul" data-filter-placeholder="{% trans %}Filter by entry type...{% endtrans %}" data-filter-theme="c" data-filter="true">
    {% set lastDate = "2170-01-01" %}
    {% for entry in entries %}
      {% set currDate = entry.added|date('Y-m-d') %}
      {% if lastDate > currDate %}
        <li data-role="list-divider">{{ currDate }}</li>
      {% endif %}
      {% set lastDate = currDate %}
      <li data-filtertext="{{ entry.typeId.name }}">
        <div class="ui-grid-c">
          <div class="ui-block-a"><strong>{{ entry.typeId.name }}</strong></div>
          <div class="ui-block-b">{{ entry.value }}</div>
          <div class="ui-block-c">{{ entry.typeId.quantity }}</div>
          <div class="ui-block-d">{{ entry.added|date('H:i') }}</div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

src/Enymind/Bundle/Health/SecureBundle/Resources/views/Default/stats.html.twig
{% extends '::base.html.twig' %}

{% block pagename %}secure-stats{% endblock %}

{% block header %}
  <a href="/secure" data-icon="back" data-theme="c">{% trans %}Back{% endtrans %}</a>
  <h1>{% trans %}Statistics{% endtrans %}</h1>
{% endblock %}

{% block body %}
  <div id="flot-container"></div>
  <div id="flot-series"></div>
{% endblock %}